Traceback (most recent call last):
  File "evaluate_siamfc.py", line 29, in <module>
    checkpoint = torch.load(args.model_path, map_location=device)
  File "/users/PAS1101/sundaralingam6/.conda/envs/siamfc/lib/python3.6/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/users/PAS1101/sundaralingam6/.conda/envs/siamfc/lib/python3.6/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/users/PAS1101/sundaralingam6/.conda/envs/siamfc/lib/python3.6/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/fs/scratch/PAS2985/team11/Pytorch-SiamFC/models/siamDroneExp_debug/best_model.pth'
